version: "3.8"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: "100M"

services:
  server:
    image: judge0/judge0:latest
    container_name: judge0-server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - db
      - redis

  worker:
    image: judge0/judge0:latest
    container_name: judge0-worker
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - server
      - db
      - redis

  db:
    image: postgres:16.2
    container_name: judge0-db
    env_file: judge0.conf
    volumes:
      - db_data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    container_name: judge0-redis
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  db_data:

